export const types = {
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
  GENERIC_ERROR: 'GENERIC_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
}
