export const types = {
  LOGIN_FAILED: 'LOGIN_FAILED',
  SIGN_UP_FAILED: 'SIGN_UP_FAILED',
  UPDATE_USER_PROFILE_FAILED: 'UPDATE_USER_PROFILE_FAILED',
  GENERIC_ERROR: 'GENERIC_ERROR',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  CREATE_NEW_PROJECT_FAILED: 'CREATE_NEW_PROJECT_FAILED',
  UPDATE_PROJECT_FAILED: 'UPDATE_PROJECT_FAILED',
  DELETE_PROJECT_FAILED: 'DELETE_PROJECT_FAILED',
}
