export const types = {
  // Synchronous
  FINISH_LOADING: 'FINISH_LOADING',
  LOGIN_SUCCESSFUL: 'LOGIN_SUCCESSFUL',
  SIGNUP_UP_SUCCESSFUL: 'SIGNUP_UP_SUCCESSFUL',
  UPDATE_USER_PROFILE_SUCCESS: 'UPDATE_USER_PROFILE_SUCCESS',
  LOGOUT: 'LOGOUT',
  SET_DONT_REMEMBER: 'SET_DONT_REMEMBER',
  UPDATE_USER_DATA: 'UPDATE_USER_DATA',

  // Asynchronous
  LOGIN_ASYNC: 'LOGIN_ASYNC',
  SIGNUP_ASYNC: 'SIGNUP_ASYNC',
  CLEAR_ERRORS: 'CLEAR_ERRORS',
  UPDATE_USER_PROFILE_ASYNC: 'UPDATE_USER_PROFILE_ASYNC',
}
