export const types = {
  ACCOUNT_UPDATED: 'ALERT_ACCOUNT_UPDATED',
  CLEAR_ALERTS: 'CLEAR_ALERTS',
  CREATE_NEW_EXTENSION_SUCCESS: 'ALERT_CREATE_NEW_EXTENSION_SUCCESS',
  DELETE_EXTENSION_SUCCESS: 'ALERT_DELETE_EXTENSION_SUCCESS',
}
