export const types = {
  ACCOUNT_UPDATED: 'ALERT_ACCOUNT_UPDATED',
  CLEAR_ALERTS: 'CLEAR_ALERTS',
  CREATE_NEW_PROJECT_SUCCESS: 'ALERT_CREATE_NEW_PROJECT_SUCCESS',
  DELETE_PROJECT_SUCCESS: 'ALERT_DELETE_PROJECT_SUCCESS',
}
